lib{pdjson}: {h c}{** -version} h{version}

# Include the generated version header into the distribution (so that we don't
# pick up an installed one) and don't remove it when cleaning in src (so that
# clean results in a state identical to distributed).
#
h{version}: in{version} $src_root/manifest
{
  dist  = true
  clean = ($src_root != $out_root)
}

# Build options.
#
c.poptions =+ "-I$out_root" "-I$src_root"

obja{*}: c.poptions += -DLIBPDJSON_STATIC_BUILD
objs{*}: c.poptions += -DLIBPDJSON_SHARED_BUILD

# Export options.
#
lib{pdjson}: c.export.poptions = "-I$out_root" "-I$src_root"

liba{pdjson}: c.export.poptions += -DLIBPDJSON_STATIC
libs{pdjson}: c.export.poptions += -DLIBPDJSON_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{pdjson}: bin.lib.version = @"-$version.project_id"
else
  lib{pdjson}: bin.lib.version = @"-$version.major.$version.minor"

# Install into the libpdjson/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{h}{*}:
{
  install         = include/libpdjson/
  install.subdirs = true
}
